brt_data:
  outputs:

    dev:
          type: postgres
          threads: 1
          host: localhost
          port: 5432
          user: postgres
          pass: postgres_password
          dbname: brt-gps
          schema: raw
  target: dev


